#!/usr/bin/env python3
"""Generate the REST endpoint reference from the FastAPI app.

Usage:
    python scripts/gen_api_docs.py              # write to docs/api/rest.md
    python scripts/gen_api_docs.py --check      # exit 1 if the page is stale
    python scripts/gen_api_docs.py --stdout     # print instead of writing

Reads the app's own OpenAPI schema rather than walking ``app.routes``: included
routers stay lazy there, so iterating routes sees only the handlers defined
directly on the app.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

OUTPUT = ROOT / "docs" / "api" / "rest.md"

_METHODS = ("get", "post", "put", "patch", "delete")

#: Tag -> heading. Anything unlisted falls back to the tag itself.
_GROUP_TITLES = {
    "health": "Health",
    "memory": "Memory",
    "brain": "Brains",
    "consolidation": "Consolidation",
    "sync": "Sync",
    "hub": "Sync hub",
    "dashboard": "Dashboard",
    "reasoning": "Reasoning training",
    "oauth": "OAuth",
    "openclaw": "OpenClaw",
    "visualization": "Visualization",
}


def _operations(spec: dict[str, Any]) -> list[tuple[str, str, str, str]]:
    """Return (tag, method, path, summary), sorted."""
    rows: list[tuple[str, str, str, str]] = []
    for path, operations in spec.get("paths", {}).items():
        for method, operation in operations.items():
            if method not in _METHODS:
                continue
            tags = operation.get("tags") or ["other"]
            rows.append((str(tags[0]), method.upper(), str(path), operation.get("summary") or ""))
    return sorted(rows, key=lambda r: (r[0], r[2], r[1]))


def generate() -> str:
    from surreal_memory.server.app import create_app

    spec = create_app().openapi()
    rows = _operations(spec)

    grouped: dict[str, list[tuple[str, str, str, str]]] = {}
    for row in rows:
        grouped.setdefault(row[0], []).append(row)

    lines: list[str] = [
        "# REST Endpoints",
        "",
        "Every HTTP endpoint the server exposes, generated from its OpenAPI schema.",
        "",
        "A running server serves the same schema interactively at `/docs` (Swagger) and",
        "`/redoc`, including request and response bodies. This page is the flat index.",
        "",
        '!!! note "Two paths reach most handlers"',
        "",
        "    The memory, brain, sync, consolidation and hub routers are mounted twice:",
        "    once under `/api/v1` and once unprefixed for backward compatibility.",
        "",
    ]

    for tag in sorted(grouped):
        lines.append(f"## {_GROUP_TITLES.get(tag, tag.replace('_', ' ').title())}")
        lines.append("")
        lines.append("| Method | Path | Summary |")
        lines.append("|---|---|---|")
        for _tag, method, path, summary in grouped[tag]:
            lines.append(f"| `{method}` | `{path}` | {summary} |")
        lines.append("")

    lines.extend(
        [
            "---",
            "",
            "*Auto-generated by `scripts/gen_api_docs.py` from the FastAPI OpenAPI schema — "
            f"{len(rows)} operations across {len(grouped)} groups.*",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate the REST endpoint reference")
    parser.add_argument("--check", action="store_true", help="Check if the page is up-to-date")
    parser.add_argument("--stdout", action="store_true", help="Print to stdout")
    args = parser.parse_args()

    content = generate()
    rel = OUTPUT.relative_to(ROOT)

    if args.stdout:
        print(content)
        return

    if args.check:
        if not OUTPUT.exists():
            print(f"  {rel} does not exist — generate with: python scripts/gen_api_docs.py")
            sys.exit(1)
        if OUTPUT.read_text(encoding="utf-8") != content:
            print(f"  {rel} is STALE — regenerate with: python scripts/gen_api_docs.py")
            sys.exit(1)
        print(f"  {rel} is up-to-date ({len(content)} chars)")
        return

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Generated {rel} ({len(content)} chars)")


if __name__ == "__main__":
    main()
