"""Surface file resolver — finds the correct .nm file for the current context.

Searches project-level first, then global. Handles Windows/Unix paths.
"""

from __future__ import annotations

import logging
import os
import re
from pathlib import Path

logger = logging.getLogger(__name__)


_BRAIN_NAME_RE = re.compile(r"^[A-Za-z0-9_.-]{1,128}$")

# Reserved device names on Windows. They are plain ASCII, so the charset above
# lets them through, and `CON.nm` there names the console device rather than a
# file -- the surface would silently fail to persist.
_WINDOWS_RESERVED = frozenset(
    {"con", "prn", "aux", "nul"}
    | {f"com{i}" for i in range(1, 10)}
    | {f"lpt{i}" for i in range(1, 10)}
)


def validate_brain_name(brain_name: str) -> str:
    """Return ``brain_name`` if it is safe to put in a file path.

    The global surface path is built as ``surfaces/<brain_name>.nm``, so an
    unvalidated name is a path-traversal primitive and, more prosaically, a way
    to write a file literally called ``CLIConfig(data_dir=PosixPath(...)).nm``
    -- which is what a live install ended up with when a config object was
    passed where a name was expected.

    Args:
        brain_name: Candidate brain name.

    Returns:
        The same name, unchanged.

    Raises:
        ValueError: If the name is empty, over 128 chars, contains anything
            outside ``[A-Za-z0-9_.-]`` (which excludes ``/``, ``\\`` and ``..``),
            or is a reserved device name.
    """
    if (
        not _BRAIN_NAME_RE.match(brain_name or "")
        or brain_name in {".", ".."}
        or brain_name.split(".", 1)[0].lower() in _WINDOWS_RESERVED
    ):
        raise ValueError(
            f"Invalid brain name {brain_name!r}: expected 1-128 characters from "
            "[A-Za-z0-9_.-], and not a reserved device name"
        )
    return brain_name


def get_surface_path(
    brain_name: str = "default",
    *,
    for_write: bool = False,
    global_only: bool = False,
) -> Path:
    """Resolve the surface.nm file path for a given brain.

    Priority:
    1. Project-level: ``<project_root>/.surrealmemory/surface.nm``
    2. Global: ``~/.surrealmemory/surfaces/<brain_name>.nm``

    For reads, project-level is returned only if the file exists.
    For writes (``for_write=True``), project-level is returned whenever
    a project root is detected — this ensures the first save creates
    the file at project level instead of always falling through to global.

    Read and write therefore agree on the same file as long as they resolve the
    same project root: outside a project both land on the global path, and inside
    one the reader picks up whatever the writer created. See
    ``detect_project_root`` for why the home directory is not a project.

    Args:
        brain_name: Brain to resolve surface for.
        for_write: If True, prefer project path even when file doesn't exist yet.
        global_only: Skip project detection entirely and return the global path.
            Project detection reads the process CWD, so a surface generated by a
            long-lived server or an MCP client inherits whatever directory that
            process happens to sit in. Callers that want one predictable
            location pass this.

    Returns:
        Path to the surface file (may not exist yet for writes).
    """
    if global_only:
        return _global_surface_path(brain_name)

    project_root = detect_project_root()
    if project_root is not None:
        project_surface = project_root / ".surrealmemory" / "surface.nm"
        if for_write or project_surface.exists():
            return project_surface

    return _global_surface_path(brain_name)


def _global_surface_path(brain_name: str = "default") -> Path:
    """Return the global surface path for a brain."""
    from surreal_memory.unified_config import get_surrealmemory_dir

    # The name becomes a filename, so it is validated here rather than trusting
    # every caller to have done it.
    return get_surrealmemory_dir() / "surfaces" / f"{validate_brain_name(brain_name)}.nm"


_NM_DIR = ".surrealmemory"

_PROJECT_MARKERS: tuple[str, ...] = (
    _NM_DIR,
    ".git",
    "pyproject.toml",
    "package.json",
    "Cargo.toml",
    "go.mod",
)


def _global_config_dir() -> Path | None:
    """Resolve the global ``.surrealmemory`` directory, or None if unavailable."""
    from surreal_memory.unified_config import get_surrealmemory_dir

    try:
        return get_surrealmemory_dir().resolve()
    except (OSError, RuntimeError):
        return None


def _is_project_root(candidate: Path, global_dir: Path | None) -> bool:
    """Check whether a directory carries a project marker."""
    for marker in _PROJECT_MARKERS:
        marker_path = candidate / marker
        if not marker_path.exists():
            continue

        # The global config directory is itself named ``.surrealmemory``, so a bare
        # existence check would promote whatever contains it (normally $HOME) to a
        # project root. Only a *project's own* .surrealmemory counts.
        if marker == _NM_DIR and global_dir is not None:
            try:
                if marker_path.resolve() == global_dir:
                    continue
            except OSError:
                pass

        return True

    return False


def detect_project_root() -> Path | None:
    """Detect the project root directory.

    Walks up from CWD looking for common project markers.
    Returns None if no project root found (e.g., in home directory) — callers
    then fall back to the global surface.

    Markers (first match wins):
    - ``.surrealmemory/`` directory (NM project config)
    - ``.git/`` directory
    - ``pyproject.toml``
    - ``package.json``
    - ``Cargo.toml``
    - ``go.mod``

    The home directory is never a project root, and neither is the parent of the
    global config directory wherever ``SURREAL_MEMORY_DIR`` points it. Matching
    ``~/.surrealmemory`` as a project marker made the resolved surface depend on
    the shell's cwd: ``surface generate`` run from ``~`` wrote
    ``~/.surrealmemory/surface.nm`` while ``doctor`` run from a repo checkout
    looked for ``~/.surrealmemory/surfaces/<brain>.nm`` and reported the surface as
    never generated. Per-project surfaces stay supported — a repo checkout with its
    own ``.surrealmemory/`` (or any other marker) is still a project root.
    """
    try:
        current = Path.cwd().resolve()
    except OSError:
        return None

    try:
        home: Path | None = Path.home().resolve()
    except (OSError, RuntimeError):
        home = None

    global_dir = _global_config_dir()

    # Walk up, but don't go above home or root
    for _ in range(20):  # safety cap
        if current != home and _is_project_root(current, global_dir):
            return current

        parent = current.parent
        if parent == current or current == home:
            break
        current = parent

    return None


def load_surface_text(brain_name: str = "default", *, global_only: bool = False) -> str | None:
    """Load surface.nm content if it exists.

    Args:
        brain_name: Brain name to resolve.
        global_only: Read the global path regardless of the caller's CWD.

    Returns:
        File content as string, or None if not found/unreadable.
    """
    path = get_surface_path(brain_name, global_only=global_only)
    if not path.exists():
        return None

    try:
        return path.read_text(encoding="utf-8")
    except OSError:
        logger.debug("Failed to read surface file: %s", path, exc_info=True)
        return None


def save_surface_text(
    text: str,
    brain_name: str = "default",
    *,
    global_only: bool = False,
) -> Path:
    """Write surface.nm content atomically.

    Creates parent directories if needed. Uses write-then-rename
    for atomic updates on supported platforms.

    Args:
        text: The .nm file content to write.
        brain_name: Brain name to resolve path for.
        global_only: Write to the global path regardless of the caller's CWD.

    Returns:
        Path where the file was written.
    """
    path = get_surface_path(brain_name, for_write=True, global_only=global_only)
    path.parent.mkdir(parents=True, exist_ok=True)

    # Warn once if both project and global surfaces exist (stale global copy)
    global_path = _global_surface_path(brain_name)
    if path != global_path and global_path.exists():
        logger.info(
            "Project surface at %s takes priority; global copy at %s is now stale",
            path,
            global_path,
        )

    # Atomic write: write to temp, then rename
    tmp_path = path.with_suffix(".nm.tmp")
    try:
        tmp_path.write_text(text, encoding="utf-8")
        # On Windows, target must not exist for rename
        if os.name == "nt" and path.exists():
            path.unlink()
        tmp_path.rename(path)
    except OSError:
        # Fallback: direct write
        logger.debug("Atomic write failed, falling back to direct write", exc_info=True)
        path.write_text(text, encoding="utf-8")
        if tmp_path.exists():
            tmp_path.unlink(missing_ok=True)

    return path
