"""Unit tests for the RetrievalTrace model (schema v9, U1)."""

from __future__ import annotations

from dataclasses import FrozenInstanceError

import pytest

from surreal_memory.core.retrieval_trace import RetrievalTrace


class TestRetrievalTrace:
    def test_defaults(self) -> None:
        rt = RetrievalTrace(brain_id="b1")
        assert rt.brain_id == "b1"
        assert rt.id  # uuid autogenerated, non-empty
        assert rt.created_at is not None
        assert rt.fiber_ids == ()
        assert rt.anchor_ids == ()
        assert rt.trace_version >= 1

    def test_frozen(self) -> None:
        rt = RetrievalTrace(brain_id="b1")
        with pytest.raises(FrozenInstanceError):
            rt.brain_id = "b2"  # type: ignore[misc]

    def test_query_truncated_to_500(self) -> None:
        rt = RetrievalTrace(brain_id="b1", query="x" * 1000)
        assert len(rt.query) <= 500

    def test_fiber_ids_capped_at_10(self) -> None:
        rt = RetrievalTrace(brain_id="b1", fiber_ids=tuple(f"f{i}" for i in range(50)))
        assert len(rt.fiber_ids) <= 10

    def test_anchor_ids_capped_at_10(self) -> None:
        rt = RetrievalTrace(brain_id="b1", anchor_ids=tuple(f"a{i}" for i in range(50)))
        assert len(rt.anchor_ids) <= 10

    def test_to_dict_from_dict_round_trip(self) -> None:
        rt = RetrievalTrace(
            brain_id="b1",
            session_id="s1",
            query="q",
            depth_used=2,
            mode="deep",
            confidence=0.8,
            latency_ms=12.5,
            anchor_ids=("a1",),
            retrievers=("bm25", "vector"),
            fiber_ids=("f1", "f2"),
            fiber_scores=(0.9, 0.5),
            filters={"tags": ["x"]},
            config_snapshot={"trust_weight": 0.0},
        )
        d = rt.to_dict()
        rt2 = RetrievalTrace.from_dict(d)
        assert rt2.brain_id == rt.brain_id
        assert rt2.session_id == rt.session_id
        assert rt2.query == rt.query
        assert rt2.depth_used == rt.depth_used
        assert rt2.mode == rt.mode
        assert rt2.confidence == rt.confidence
        assert rt2.latency_ms == rt.latency_ms
        assert rt2.fiber_ids == rt.fiber_ids
        assert rt2.fiber_scores == rt.fiber_scores
        assert rt2.retrievers == rt.retrievers
        assert rt2.filters == rt.filters
        assert rt2.config_snapshot == rt.config_snapshot

    def test_from_dict_tolerates_missing_keys(self) -> None:
        rt = RetrievalTrace.from_dict({"brain_id": "b1"})
        assert rt.brain_id == "b1"
        assert rt.fiber_ids == ()
